import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
];

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    addCrop: 'Add Crop',
    orders: 'Orders',
    marketplace: 'Marketplace',
    myOrders: 'My Orders',
    online: 'Online',
    offline: 'Offline',
    logout: 'Logout',
    language: 'Language',

    // Common
    farmer: 'Farmer',
    retailer: 'Retailer',
    transporter: 'Transporter',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    edit: 'Edit',
    retry: 'Retry',
    back: 'Back',
    search: 'Search',
    noResults: 'No results found',

    // Landing
    heroTagline: 'Empowering Indian Farmers',
    heroTitle1: 'Farm to Retail,',
    heroTitle2: 'No Middlemen',
    heroDesc: 'Connect directly with retailers and transporters. Fair prices. Transparent logistics. Works even offline.',
    getStarted: 'Get Started',
    createAccount: 'Create Account',
    builtForEveryone: 'Built for Everyone in the Supply Chain',
    builtForEveryoneDesc: 'Whether you grow, buy, or deliver — AgroX has you covered.',
    farmerRoleDesc: 'List your crops, get fair prices, track orders & payments',
    retailerRoleDesc: 'Browse fresh produce, order directly, pay via UPI',
    transporterRoleDesc: 'Accept delivery jobs, track routes, earn income',
    whyMandiConnect: 'Why AgroX?',
    offlineFirst: 'Offline-First',
    offlineFirstDesc: 'Add crops even without internet. Data syncs automatically.',
    fairPricing: 'Fair Pricing',
    fairPricingDesc: 'No middlemen means better margins for farmers.',
    smartLogistics: 'Smart Logistics',
    smartLogisticsDesc: 'Coordinated delivery matching for efficient transport.',
    mobileReady: 'Mobile Ready',
    mobileReadyDesc: 'Designed for phones with large touch targets.',
    upiPayments: 'UPI Payments',
    upiPaymentsDesc: 'Simple, secure payment flow built for India.',
    marketInsights: 'Market Insights',
    marketInsightsDesc: 'Demand heatmaps and price predictions at a glance.',
    readyToStart: 'Ready to Get Started?',
    readyToStartDesc: 'Join thousands of farmers, retailers, and transporters building a fairer marketplace.',
    createFreeAccount: 'Create Free Account',
    login: 'Login',

    // Auth
    welcomeBack: 'Welcome Back',
    verifyOTP: 'Verify OTP',
    signInSubtitle: 'Sign in to your AgroX account',
    otpSentTo: 'OTP sent to',
    iAmA: 'I am a',
    phoneNumber: 'Phone Number',
    sendOTP: 'Send OTP',
    sendingOTP: 'Sending OTP...',
    newHere: 'New here?',
    createAnAccount: 'Create an account',
    enter4DigitOTP: 'Enter 4-digit OTP',
    demoOTP: 'Demo OTP:',
    resendOTPIn: 'Resend OTP in',
    resendOTP: 'Resend OTP',
    verifying: 'Verifying...',
    verifySignIn: 'Verify & Sign In',
    changePhoneNumber: 'Change phone number',
    pleaseEnterOTP: 'Please enter the 4-digit OTP',
    joinMandiConnect: 'Join AgroX in seconds',
    fullName: 'Full Name',
    enterYourName: 'Enter your name',
    location: 'Location',
    villageCityPlaceholder: 'Village / City',
    vehicleType: 'Vehicle Type',
    verifyPhoneRegister: 'Verify Phone & Register',
    alreadyRegistered: 'Already registered?',
    signIn: 'Sign in',
    verifyCreateAccount: 'Verify & Create Account',
    backToDetails: 'Back to details',

    // Farmer Dashboard
    welcome: 'Welcome',
    totalCrops: 'Total Crops',
    available: 'Available',
    sold: 'Sold',
    pendingSync: 'Pending Sync',
    demandHeatmap: 'Demand Heatmap',
    demoData: 'Demo Data',
    pricePredictions: 'Price Predictions',
    nextWeek: 'Next week:',
    placeholderPredictions: '* Placeholder predictions for demonstration',
    yourListedCrops: 'Your Listed Crops',
    noCropsListed: 'No crops listed yet',
    startByAdding: 'Start by adding your first crop listing',
    addYourFirstCrop: 'Add Your First Crop',

    // Add Crop
    listProduce: 'List your produce for retailers to discover',
    youreOffline: "You're offline",
    cropSavedLocally: 'Crop will be saved locally and synced later',
    cropName: 'Crop Name',
    cropPhoto: 'Crop Photo',
    tapToPhoto: 'Tap to take a photo',
    chooseGallery: 'or choose from gallery',
    photoAdded: 'Photo added',
    quantity: 'Quantity',
    pricePerUnit: 'Price per',
    pickupLocation: 'Pickup Location',
    detectingLocation: 'Detecting your location...',
    couldntDetect: "Couldn't detect location",
    villageMandi: 'Village / Mandi name',
    editLocation: 'Edit location',
    pickOnMap: 'Pick on Map',
    detectViaGPS: 'Detect via GPS',
    availableUntil: 'Available Until',
    totalValue: 'Total Value',
    cropListed: 'Crop listed successfully!',
    savedOffline: 'Saved offline. Will sync when online.',
    saving: 'Saving...',
    listCrop: 'List Crop',
    saveOffline: 'Save Offline',

    // Marketplace
    cropMarketplace: 'Crop Marketplace',
    browseAndOrder: 'Browse and order fresh produce directly from farmers',
    cropNameFilter: 'Crop name',
    locationFilter: 'Location',
    minPrice: 'Min ₹',
    maxPrice: 'Max ₹',
    searchCrops: 'Search Crops',
    cropsAvailable: 'crops available',
    noCropsFound: 'No crops found',
    tryAdjusting: 'Try adjusting your filters or check back later',
    orderNow: 'Order Now',

    // Order Page
    placeOrder: 'Place Order',
    reviewCrop: 'Review crop details and confirm your order',
    cropNotFound: 'Crop details not found',
    cropMayNotAvail: 'This crop may no longer be available',
    backToMarketplace: 'Back to Marketplace',
    howMuch: 'How much do you need?',
    maxAvailable: 'Max available:',
    deliveryLocation: 'Delivery Location',
    warehouseShop: 'Your warehouse / shop',
    estimatedTotal: 'Estimated Total',
    orderPlaced: 'Order Placed!',
    total: 'Total',
    payNow: 'Pay Now',
    placingOrder: 'Placing Order...',
    confirmOrder: 'Confirm Order',

    // Farmer Orders
    yourOrders: 'Your Orders',
    manageOrders: 'Manage orders from retailers',
    pending: 'Pending',
    active: 'Active',
    accept: 'Accept',
    reject: 'Reject',
    noOrdersYet: 'No orders yet',
    ordersWillAppear: 'Orders from retailers will appear here',

    // Retailer Orders
    trackOrders: 'Track your placed orders and payments',
    unpaid: 'Unpaid',
    paid: 'Paid',
    browseMarketplace: 'Browse the marketplace to place your first order',

    // Transporter
    transporterDashboard: 'Transporter Dashboard',
    completed: 'Completed',
    myJobs: 'My Jobs',
    delivery: 'Delivery',
    orderValue: 'Order value:',
    pickup: 'Pickup',
    dropOff: 'Drop-off',
    acceptJob: 'Accept Job',
    noDeliveryRequests: 'No delivery requests right now',
    checkBackLater: 'Check back later for new jobs',
    noActiveJobs: 'No active jobs',
    acceptAvailableJobs: 'Accept available jobs to get started',
    startTransit: 'Start Transit',
    markDelivered: 'Mark Delivered',
    deliveryCompleted: 'Delivery Completed',
    inProgress: 'In progress',

    // Payment
    payment: 'Payment',
    completePayment: 'Complete your order payment',
    amountToPay: 'Amount to Pay',
    connectedParties: 'Connected Parties',
    paymentSplitPreview: 'Payment Split Preview',
    paymentMethod: 'Payment Method',
    paymentSuccess: 'Payment Successful!',
    transactionId: 'Transaction ID',
  },

  hi: {
    dashboard: 'डैशबोर्ड',
    addCrop: 'फसल जोड़ें',
    orders: 'ऑर्डर',
    marketplace: 'बाज़ार',
    myOrders: 'मेरे ऑर्डर',
    online: 'ऑनलाइन',
    offline: 'ऑफ़लाइन',
    logout: 'लॉग आउट',
    language: 'भाषा',
    farmer: 'किसान',
    retailer: 'व्यापारी',
    transporter: 'ट्रांसपोर्टर',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    edit: 'संपादित करें',
    retry: 'पुनः प्रयास',
    back: 'वापस',
    search: 'खोजें',
    noResults: 'कोई परिणाम नहीं मिला',
    heroTagline: 'भारतीय किसानों को सशक्त बनाना',
    heroTitle1: 'खेत से बाज़ार,',
    heroTitle2: 'बिना बिचौलिए',
    heroDesc: 'व्यापारियों और ट्रांसपोर्टरों से सीधे जुड़ें। उचित मूल्य। पारदर्शी लॉजिस्टिक्स। ऑफ़लाइन भी काम करता है।',
    getStarted: 'शुरू करें',
    createAccount: 'खाता बनाएं',
    builtForEveryone: 'आपूर्ति श्रृंखला में सभी के लिए बना',
    builtForEveryoneDesc: 'चाहे आप उगाते हों, खरीदते हों या पहुंचाते हों — AgroX आपके साथ है।',
    farmerRoleDesc: 'अपनी फसलें सूचीबद्ध करें, उचित मूल्य पाएं, ऑर्डर और भुगतान ट्रैक करें',
    retailerRoleDesc: 'ताजा उपज ब्राउज़ करें, सीधे ऑर्डर करें, UPI से भुगतान करें',
    transporterRoleDesc: 'डिलीवरी जॉब स्वीकार करें, रूट ट्रैक करें, आय अर्जित करें',
    whyMandiConnect: 'AgroX क्यों?',
    offlineFirst: 'ऑफ़लाइन-फ़र्स्ट',
    offlineFirstDesc: 'बिना इंटरनेट के भी फसल जोड़ें। डेटा स्वचालित सिंक होता है।',
    fairPricing: 'उचित मूल्य',
    fairPricingDesc: 'बिचौलिए नहीं, किसानों को अधिक मुनाफा।',
    smartLogistics: 'स्मार्ट लॉजिस्टिक्स',
    smartLogisticsDesc: 'कुशल परिवहन के लिए समन्वित डिलीवरी।',
    mobileReady: 'मोबाइल रेडी',
    mobileReadyDesc: 'बड़े टच टारगेट के साथ फोन के लिए डिज़ाइन किया गया।',
    upiPayments: 'UPI भुगतान',
    upiPaymentsDesc: 'भारत के लिए सरल, सुरक्षित भुगतान।',
    marketInsights: 'बाज़ार जानकारी',
    marketInsightsDesc: 'मांग हीटमैप और मूल्य भविष्यवाणी एक नज़र में।',
    readyToStart: 'शुरू करने के लिए तैयार?',
    readyToStartDesc: 'हजारों किसानों, व्यापारियों और ट्रांसपोर्टरों से जुड़ें।',
    createFreeAccount: 'मुफ्त खाता बनाएं',
    login: 'लॉगिन',
    welcomeBack: 'वापसी पर स्वागत',
    verifyOTP: 'OTP सत्यापित करें',
    signInSubtitle: 'अपने AgroX खाते में साइन इन करें',
    otpSentTo: 'OTP भेजा गया',
    iAmA: 'मैं हूँ',
    phoneNumber: 'फ़ोन नंबर',
    sendOTP: 'OTP भेजें',
    sendingOTP: 'OTP भेज रहे हैं...',
    newHere: 'नए हैं?',
    createAnAccount: 'खाता बनाएं',
    enter4DigitOTP: '4 अंकों का OTP दर्ज करें',
    demoOTP: 'डेमो OTP:',
    resendOTPIn: 'OTP पुनः भेजें',
    resendOTP: 'OTP पुनः भेजें',
    verifying: 'सत्यापित हो रहा है...',
    verifySignIn: 'सत्यापित करें और साइन इन करें',
    changePhoneNumber: 'फ़ोन नंबर बदलें',
    pleaseEnterOTP: 'कृपया 4 अंकों का OTP दर्ज करें',
    joinMandiConnect: 'AgroX से सेकंडों में जुड़ें',
    fullName: 'पूरा नाम',
    enterYourName: 'अपना नाम दर्ज करें',
    location: 'स्थान',
    villageCityPlaceholder: 'गाँव / शहर',
    vehicleType: 'वाहन प्रकार',
    verifyPhoneRegister: 'फ़ोन सत्यापित करें और पंजीकरण करें',
    alreadyRegistered: 'पहले से पंजीकृत?',
    signIn: 'साइन इन',
    verifyCreateAccount: 'सत्यापित करें और खाता बनाएं',
    backToDetails: 'विवरण पर वापस जाएं',
    welcome: 'स्वागत है',
    totalCrops: 'कुल फसलें',
    available: 'उपलब्ध',
    sold: 'बिकी हुई',
    pendingSync: 'सिंक बाकी',
    demandHeatmap: 'मांग हीटमैप',
    demoData: 'डेमो डेटा',
    pricePredictions: 'मूल्य भविष्यवाणी',
    nextWeek: 'अगले हफ्ते:',
    placeholderPredictions: '* प्रदर्शन हेतु अनुमानित भविष्यवाणियाँ',
    yourListedCrops: 'आपकी सूचीबद्ध फसलें',
    noCropsListed: 'अभी कोई फसल सूचीबद्ध नहीं',
    startByAdding: 'अपनी पहली फसल सूचीबद्ध करें',
    addYourFirstCrop: 'पहली फसल जोड़ें',
    listProduce: 'व्यापारियों के लिए अपनी उपज सूचीबद्ध करें',
    youreOffline: 'आप ऑफ़लाइन हैं',
    cropSavedLocally: 'फसल स्थानीय रूप से सहेजी जाएगी और बाद में सिंक होगी',
    cropName: 'फसल का नाम',
    cropPhoto: 'फसल की फोटो',
    tapToPhoto: 'फोटो लेने के लिए टैप करें',
    chooseGallery: 'या गैलरी से चुनें',
    photoAdded: 'फोटो जोड़ी गई',
    quantity: 'मात्रा',
    pricePerUnit: 'प्रति मूल्य',
    pickupLocation: 'पिकअप स्थान',
    detectingLocation: 'आपका स्थान पता लगा रहे हैं...',
    couldntDetect: 'स्थान पता नहीं चला',
    villageMandi: 'गाँव / मंडी का नाम',
    editLocation: 'स्थान संपादित करें',
    pickOnMap: 'मानचित्र पर चुनें',
    detectViaGPS: 'GPS से पता लगाएं',
    availableUntil: 'उपलब्धता तिथि',
    totalValue: 'कुल मूल्य',
    cropListed: 'फसल सफलतापूर्वक सूचीबद्ध!',
    savedOffline: 'ऑफ़लाइन सहेजा गया। ऑनलाइन होने पर सिंक होगा।',
    saving: 'सहेज रहे हैं...',
    listCrop: 'फसल सूचीबद्ध करें',
    saveOffline: 'ऑफ़लाइन सहेजें',
    cropMarketplace: 'फसल बाज़ार',
    browseAndOrder: 'किसानों से सीधे ताजा उपज ब्राउज़ करें और ऑर्डर करें',
    cropNameFilter: 'फसल का नाम',
    locationFilter: 'स्थान',
    minPrice: 'न्यूनतम ₹',
    maxPrice: 'अधिकतम ₹',
    searchCrops: 'फसलें खोजें',
    cropsAvailable: 'फसलें उपलब्ध',
    noCropsFound: 'कोई फसल नहीं मिली',
    tryAdjusting: 'फिल्टर बदलें या बाद में देखें',
    orderNow: 'अभी ऑर्डर करें',
    placeOrder: 'ऑर्डर दें',
    reviewCrop: 'फसल विवरण देखें और ऑर्डर पुष्टि करें',
    cropNotFound: 'फसल विवरण नहीं मिला',
    cropMayNotAvail: 'यह फसल अब उपलब्ध नहीं हो सकती',
    backToMarketplace: 'बाज़ार पर वापस जाएं',
    howMuch: 'आपको कितना चाहिए?',
    maxAvailable: 'अधिकतम उपलब्ध:',
    deliveryLocation: 'डिलीवरी स्थान',
    warehouseShop: 'आपका गोदाम / दुकान',
    estimatedTotal: 'अनुमानित कुल',
    orderPlaced: 'ऑर्डर हो गया!',
    total: 'कुल',
    payNow: 'अभी भुगतान करें',
    placingOrder: 'ऑर्डर दे रहे हैं...',
    confirmOrder: 'ऑर्डर पुष्टि करें',
    yourOrders: 'आपके ऑर्डर',
    manageOrders: 'व्यापारियों के ऑर्डर प्रबंधित करें',
    pending: 'लंबित',
    active: 'सक्रिय',
    accept: 'स्वीकार करें',
    reject: 'अस्वीकार करें',
    noOrdersYet: 'अभी कोई ऑर्डर नहीं',
    ordersWillAppear: 'व्यापारियों के ऑर्डर यहाँ दिखेंगे',
    trackOrders: 'अपने ऑर्डर और भुगतान ट्रैक करें',
    unpaid: 'अवैतनिक',
    paid: 'भुगतान किया',
    browseMarketplace: 'अपना पहला ऑर्डर देने के लिए बाज़ार ब्राउज़ करें',
    transporterDashboard: 'ट्रांसपोर्टर डैशबोर्ड',
    completed: 'पूर्ण',
    myJobs: 'मेरे जॉब',
    delivery: 'डिलीवरी',
    orderValue: 'ऑर्डर मूल्य:',
    pickup: 'पिकअप',
    dropOff: 'ड्राप-ऑफ',
    acceptJob: 'जॉब स्वीकार करें',
    noDeliveryRequests: 'अभी कोई डिलीवरी अनुरोध नहीं',
    checkBackLater: 'नए जॉब के लिए बाद में देखें',
    noActiveJobs: 'कोई सक्रिय जॉब नहीं',
    acceptAvailableJobs: 'शुरू करने के लिए उपलब्ध जॉब स्वीकार करें',
    startTransit: 'ट्रांज़िट शुरू करें',
    markDelivered: 'डिलीवर हुआ',
    deliveryCompleted: 'डिलीवरी पूर्ण',
    inProgress: 'प्रगति में',
    payment: 'भुगतान',
    completePayment: 'अपने ऑर्डर का भुगतान पूरा करें',
    amountToPay: 'भुगतान राशि',
    connectedParties: 'जुड़े पक्ष',
    paymentSplitPreview: 'भुगतान विभाजन दृश्य',
    paymentMethod: 'भुगतान विधि',
    paymentSuccess: 'भुगतान सफल!',
    transactionId: 'लेनदेन ID',
  },

  mr: {
    dashboard: 'डॅशबोर्ड',
    addCrop: 'पीक जोडा',
    orders: 'ऑर्डर',
    marketplace: 'बाजार',
    myOrders: 'माझे ऑर्डर',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    logout: 'लॉग आउट',
    language: 'भाषा',
    farmer: 'शेतकरी',
    retailer: 'व्यापारी',
    transporter: 'वाहतूकदार',
    loading: 'लोड होत आहे...',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    confirm: 'पुष्टी करा',
    edit: 'संपादित करा',
    retry: 'पुन्हा प्रयत्न',
    back: 'मागे',
    search: 'शोधा',
    noResults: 'कोणतेही परिणाम नाहीत',
    heroTagline: 'भारतीय शेतकऱ्यांना सक्षम करणे',
    heroTitle1: 'शेतातून बाजारात,',
    heroTitle2: 'दलाल नाही',
    heroDesc: 'व्यापारी आणि वाहतूकदारांशी थेट जोडा. योग्य किंमत. पारदर्शक लॉजिस्टिक्स. ऑफलाइनही काम करते.',
    getStarted: 'सुरू करा',
    createAccount: 'खाते तयार करा',
    builtForEveryone: 'पुरवठा साखळीतील सर्वांसाठी',
    builtForEveryoneDesc: 'तुम्ही पिकवा, विका किंवा पोहोचवा — AgroX तुमच्यासोबत आहे.',
    farmerRoleDesc: 'तुमची पिके सूचीबद्ध करा, योग्य किंमत मिळवा, ऑर्डर ट्रॅक करा',
    retailerRoleDesc: 'ताजी उत्पादने ब्राउझ करा, थेट ऑर्डर द्या, UPI ने पैसे द्या',
    transporterRoleDesc: 'डिलिव्हरी जॉब स्वीकारा, रूट ट्रॅक करा, उत्पन्न मिळवा',
    whyMandiConnect: 'AgroX का?',
    offlineFirst: 'ऑफलाइन-फर्स्ट',
    offlineFirstDesc: 'इंटरनेटशिवाय पिके जोडा. डेटा आपोआप सिंक होतो.',
    fairPricing: 'योग्य किंमत',
    fairPricingDesc: 'दलाल नाही म्हणजे शेतकऱ्यांना अधिक नफा.',
    smartLogistics: 'स्मार्ट लॉजिस्टिक्स',
    smartLogisticsDesc: 'कार्यक्षम वाहतुकीसाठी समन्वित डिलिव्हरी.',
    mobileReady: 'मोबाइल रेडी',
    mobileReadyDesc: 'फोनसाठी मोठ्या टच टार्गेटसह डिझाइन.',
    upiPayments: 'UPI पेमेंट',
    upiPaymentsDesc: 'भारतासाठी सोपे, सुरक्षित पेमेंट.',
    marketInsights: 'बाजार माहिती',
    marketInsightsDesc: 'मागणी हीटमॅप आणि किंमत अंदाज एका दृष्टीक्षेपात.',
    readyToStart: 'सुरू करायला तयार?',
    readyToStartDesc: 'हजारो शेतकरी, व्यापारी आणि वाहतूकदारांसोबत जोडा.',
    createFreeAccount: 'मोफत खाते तयार करा',
    login: 'लॉगिन',
    welcomeBack: 'पुन्हा स्वागत',
    verifyOTP: 'OTP सत्यापित करा',
    signInSubtitle: 'तुमच्या AgroX खात्यात साइन इन करा',
    otpSentTo: 'OTP पाठवला',
    iAmA: 'मी आहे',
    phoneNumber: 'फोन नंबर',
    sendOTP: 'OTP पाठवा',
    sendingOTP: 'OTP पाठवत आहे...',
    newHere: 'नवीन आहात?',
    createAnAccount: 'खाते तयार करा',
    enter4DigitOTP: '4 अंकी OTP टाका',
    demoOTP: 'डेमो OTP:',
    resendOTPIn: 'OTP पुन्हा पाठवा',
    resendOTP: 'OTP पुन्हा पाठवा',
    verifying: 'सत्यापित होत आहे...',
    verifySignIn: 'सत्यापित करा आणि साइन इन करा',
    changePhoneNumber: 'फोन नंबर बदला',
    pleaseEnterOTP: 'कृपया 4 अंकी OTP टाका',
    joinMandiConnect: 'AgroX सोबत सेकंदात जोडा',
    fullName: 'पूर्ण नाव',
    enterYourName: 'तुमचे नाव टाका',
    location: 'स्थान',
    villageCityPlaceholder: 'गाव / शहर',
    vehicleType: 'वाहन प्रकार',
    verifyPhoneRegister: 'फोन सत्यापित करा आणि नोंदणी करा',
    alreadyRegistered: 'आधीच नोंदणीकृत?',
    signIn: 'साइन इन',
    verifyCreateAccount: 'सत्यापित करा आणि खाते तयार करा',
    backToDetails: 'तपशीलांवर परत जा',
    welcome: 'स्वागत',
    totalCrops: 'एकूण पिके',
    available: 'उपलब्ध',
    sold: 'विकलेली',
    pendingSync: 'सिंक बाकी',
    demandHeatmap: 'मागणी हीटमॅप',
    demoData: 'डेमो डेटा',
    pricePredictions: 'किंमत अंदाज',
    nextWeek: 'पुढच्या आठवड्यात:',
    placeholderPredictions: '* प्रात्यक्षिकासाठी अंदाजित भविष्यवाणी',
    yourListedCrops: 'तुमची सूचीबद्ध पिके',
    noCropsListed: 'अजून कोणतेही पीक नाही',
    startByAdding: 'तुमचे पहिले पीक सूचीबद्ध करा',
    addYourFirstCrop: 'पहिले पीक जोडा',
    listProduce: 'व्यापाऱ्यांसाठी तुमची उत्पादने सूचीबद्ध करा',
    youreOffline: 'तुम्ही ऑफलाइन आहात',
    cropSavedLocally: 'पीक स्थानिक पातळीवर जतन केले जाईल',
    cropName: 'पिकाचे नाव',
    cropPhoto: 'पिकाचा फोटो',
    tapToPhoto: 'फोटो काढण्यासाठी टॅप करा',
    chooseGallery: 'किंवा गॅलरीतून निवडा',
    photoAdded: 'फोटो जोडला',
    quantity: 'प्रमाण',
    pricePerUnit: 'प्रति किंमत',
    pickupLocation: 'पिकअप स्थान',
    detectingLocation: 'तुमचे स्थान शोधत आहे...',
    couldntDetect: 'स्थान सापडले नाही',
    villageMandi: 'गाव / मंडी नाव',
    editLocation: 'स्थान संपादित करा',
    pickOnMap: 'नकाशावर निवडा',
    detectViaGPS: 'GPS ने शोधा',
    availableUntil: 'उपलब्धता तारीख',
    totalValue: 'एकूण मूल्य',
    cropListed: 'पीक यशस्वीरित्या सूचीबद्ध!',
    savedOffline: 'ऑफलाइन जतन केले. ऑनलाइन आल्यावर सिंक होईल.',
    saving: 'जतन करत आहे...',
    listCrop: 'पीक सूचीबद्ध करा',
    saveOffline: 'ऑफलाइन जतन करा',
    cropMarketplace: 'पीक बाजार',
    browseAndOrder: 'शेतकऱ्यांकडून थेट ताजी उत्पादने ब्राउझ करा',
    cropNameFilter: 'पिकाचे नाव',
    locationFilter: 'स्थान',
    minPrice: 'किमान ₹',
    maxPrice: 'कमाल ₹',
    searchCrops: 'पिके शोधा',
    cropsAvailable: 'पिके उपलब्ध',
    noCropsFound: 'कोणतेही पीक सापडले नाही',
    tryAdjusting: 'फिल्टर बदला किंवा नंतर बघा',
    orderNow: 'आता ऑर्डर द्या',
    placeOrder: 'ऑर्डर द्या',
    reviewCrop: 'पीक तपशील पाहा आणि ऑर्डर पुष्टी करा',
    cropNotFound: 'पीक तपशील सापडले नाही',
    cropMayNotAvail: 'हे पीक आता उपलब्ध नसू शकते',
    backToMarketplace: 'बाजारात परत जा',
    howMuch: 'तुम्हाला किती हवे?',
    maxAvailable: 'कमाल उपलब्ध:',
    deliveryLocation: 'डिलिव्हरी स्थान',
    warehouseShop: 'तुमचे गोदाम / दुकान',
    estimatedTotal: 'अंदाजित एकूण',
    orderPlaced: 'ऑर्डर दिला!',
    total: 'एकूण',
    payNow: 'आता पैसे द्या',
    placingOrder: 'ऑर्डर देत आहे...',
    confirmOrder: 'ऑर्डर पुष्टी करा',
    yourOrders: 'तुमचे ऑर्डर',
    manageOrders: 'व्यापाऱ्यांचे ऑर्डर व्यवस्थापित करा',
    pending: 'प्रलंबित',
    active: 'सक्रिय',
    accept: 'स्वीकारा',
    reject: 'नाकारा',
    noOrdersYet: 'अजून ऑर्डर नाही',
    ordersWillAppear: 'व्यापाऱ्यांचे ऑर्डर येथे दिसतील',
    trackOrders: 'तुमचे ऑर्डर आणि पेमेंट ट्रॅक करा',
    unpaid: 'अवैतनिक',
    paid: 'भुगतान केले',
    browseMarketplace: 'पहिला ऑर्डर देण्यासाठी बाजार ब्राउझ करा',
    transporterDashboard: 'वाहतूकदार डॅशबोर्ड',
    completed: 'पूर्ण',
    myJobs: 'माझे जॉब',
    delivery: 'डिलिव्हरी',
    orderValue: 'ऑर्डर मूल्य:',
    pickup: 'पिकअप',
    dropOff: 'ड्रॉप-ऑफ',
    acceptJob: 'जॉब स्वीकारा',
    noDeliveryRequests: 'सध्या कोणतीही डिलिव्हरी विनंती नाही',
    checkBackLater: 'नवीन जॉबसाठी नंतर बघा',
    noActiveJobs: 'कोणतेही सक्रिय जॉब नाहीत',
    acceptAvailableJobs: 'सुरू करण्यासाठी उपलब्ध जॉब स्वीकारा',
    startTransit: 'ट्रान्झिट सुरू करा',
    markDelivered: 'डिलिव्हर झाले',
    deliveryCompleted: 'डिलिव्हरी पूर्ण',
    inProgress: 'प्रगतीपथावर',
    payment: 'पेमेंट',
    completePayment: 'तुमच्या ऑर्डरचे पेमेंट पूर्ण करा',
    amountToPay: 'भरण्याची रक्कम',
    connectedParties: 'जोडलेले पक्ष',
    paymentSplitPreview: 'पेमेंट विभाजन दृश्य',
    paymentMethod: 'पेमेंट पद्धत',
    paymentSuccess: 'पेमेंट यशस्वी!',
    transactionId: 'व्यवहार ID',
  },

  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    addCrop: 'ಬೆಳೆ ಸೇರಿಸಿ',
    orders: 'ಆರ್ಡರ್‌ಗಳು',
    marketplace: 'ಮಾರುಕಟ್ಟೆ',
    myOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    online: 'ಆನ್‌ಲೈನ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    language: 'ಭಾಷೆ',
    farmer: 'ರೈತ',
    retailer: 'ವ್ಯಾಪಾರಿ',
    transporter: 'ಸಾಗಣೆದಾರ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಗೊಳಿಸಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    retry: 'ಮರುಪ್ರಯತ್ನಿಸಿ',
    back: 'ಹಿಂದೆ',
    search: 'ಹುಡುಕಿ',
    noResults: 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಕಂಡುಬಂದಿಲ್ಲ',
    heroTagline: 'ಭಾರತೀಯ ರೈತರನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು',
    heroTitle1: 'ಹೊಲದಿಂದ ಅಂಗಡಿಗೆ,',
    heroTitle2: 'ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ',
    heroDesc: 'ವ್ಯಾಪಾರಿಗಳು ಮತ್ತು ಸಾಗಣೆದಾರರೊಂದಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ. ಉಚಿತ ಬೆಲೆ. ಪಾರದರ್ಶಕ ಲಾಜಿಸ್ಟಿಕ್ಸ್.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    createAccount: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    builtForEveryone: 'ಪೂರೈಕೆ ಸರಪಳಿಯ ಎಲ್ಲರಿಗಾಗಿ',
    builtForEveryoneDesc: 'ನೀವು ಬೆಳೆಯಿರಿ, ಖರೀದಿಸಿ ಅಥವಾ ತಲುಪಿಸಿ — AgroX ನಿಮ್ಮೊಂದಿಗಿದೆ.',
    farmerRoleDesc: 'ನಿಮ್ಮ ಬೆಳೆಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ, ಉಚಿತ ಬೆಲೆ ಪಡೆಯಿರಿ',
    retailerRoleDesc: 'ತಾಜಾ ಉತ್ಪನ್ನಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ, ನೇರವಾಗಿ ಆರ್ಡರ್ ಮಾಡಿ',
    transporterRoleDesc: 'ಡೆಲಿವರಿ ಕೆಲಸ ಸ್ವೀಕರಿಸಿ, ಮಾರ್ಗ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    whyMandiConnect: 'AgroX ಏಕೆ?',
    offlineFirst: 'ಆಫ್‌ಲೈನ್-ಫಸ್ಟ್',
    offlineFirstDesc: 'ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ ಬೆಳೆ ಸೇರಿಸಿ. ಡೇಟಾ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    fairPricing: 'ಉಚಿತ ಬೆಲೆ',
    fairPricingDesc: 'ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ ಅಂದರೆ ರೈತರಿಗೆ ಹೆಚ್ಚಿನ ಲಾಭ.',
    smartLogistics: 'ಸ್ಮಾರ್ಟ್ ಲಾಜಿಸ್ಟಿಕ್ಸ್',
    smartLogisticsDesc: 'ಪರಿಣಾಮಕಾರಿ ಸಾಗಣೆಗಾಗಿ ಸಮನ್ವಯಿತ ಡೆಲಿವರಿ.',
    mobileReady: 'ಮೊಬೈಲ್ ರೆಡಿ',
    mobileReadyDesc: 'ದೊಡ್ಡ ಟಚ್ ಟಾರ್ಗೆಟ್‌ಗಳೊಂದಿಗೆ ಫೋನ್‌ಗಾಗಿ ವಿನ್ಯಾಸ.',
    upiPayments: 'UPI ಪಾವತಿ',
    upiPaymentsDesc: 'ಭಾರತಕ್ಕಾಗಿ ಸರಳ, ಸುರಕ್ಷಿತ ಪಾವತಿ.',
    marketInsights: 'ಮಾರುಕಟ್ಟೆ ಒಳನೋಟ',
    marketInsightsDesc: 'ಬೇಡಿಕೆ ಹೀಟ್‌ಮ್ಯಾಪ್ ಮತ್ತು ಬೆಲೆ ಮುನ್ಸೂಚನೆ.',
    readyToStart: 'ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರೇ?',
    readyToStartDesc: 'ಸಾವಿರಾರು ರೈತರು ಮತ್ತು ವ್ಯಾಪಾರಿಗಳೊಂದಿಗೆ ಸೇರಿ.',
    createFreeAccount: 'ಉಚಿತ ಖಾತೆ ತೆರೆಯಿರಿ',
    login: 'ಲಾಗಿನ್',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ',
    verifyOTP: 'OTP ಪರಿಶೀಲಿಸಿ',
    signInSubtitle: 'ನಿಮ್ಮ AgroX ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    otpSentTo: 'OTP ಕಳುಹಿಸಲಾಗಿದೆ',
    iAmA: 'ನಾನು',
    phoneNumber: 'ಫೋನ್ ನಂಬರ್',
    sendOTP: 'OTP ಕಳುಹಿಸಿ',
    sendingOTP: 'OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    newHere: 'ಹೊಸಬರಾ?',
    createAnAccount: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    enter4DigitOTP: '4 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
    demoOTP: 'ಡೆಮೊ OTP:',
    resendOTPIn: 'OTP ಮರುಕಳುಹಿಸಿ',
    resendOTP: 'OTP ಮರುಕಳುಹಿಸಿ',
    verifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    verifySignIn: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    changePhoneNumber: 'ಫೋನ್ ನಂಬರ್ ಬದಲಿಸಿ',
    pleaseEnterOTP: 'ದಯವಿಟ್ಟು 4 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ',
    joinMandiConnect: 'AgroX‌ಗೆ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಸೇರಿ',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    enterYourName: 'ನಿಮ್ಮ ಹೆಸರು ನಮೂದಿಸಿ',
    location: 'ಸ್ಥಳ',
    villageCityPlaceholder: 'ಹಳ್ಳಿ / ನಗರ',
    vehicleType: 'ವಾಹನ ಪ್ರಕಾರ',
    verifyPhoneRegister: 'ಫೋನ್ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನೋಂದಾಯಿಸಿ',
    alreadyRegistered: 'ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ?',
    signIn: 'ಸೈನ್ ಇನ್',
    verifyCreateAccount: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಖಾತೆ ತೆರೆಯಿರಿ',
    backToDetails: 'ವಿವರಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    welcome: 'ಸ್ವಾಗತ',
    totalCrops: 'ಒಟ್ಟು ಬೆಳೆಗಳು',
    available: 'ಲಭ್ಯ',
    sold: 'ಮಾರಾಟ',
    pendingSync: 'ಸಿಂಕ್ ಬಾಕಿ',
    demandHeatmap: 'ಬೇಡಿಕೆ ಹೀಟ್‌ಮ್ಯಾಪ್',
    demoData: 'ಡೆಮೊ ಡೇಟಾ',
    pricePredictions: 'ಬೆಲೆ ಮುನ್ಸೂಚನೆ',
    nextWeek: 'ಮುಂದಿನ ವಾರ:',
    placeholderPredictions: '* ಪ್ರದರ್ಶನಕ್ಕಾಗಿ ಅಂದಾಜು ಮುನ್ಸೂಚನೆ',
    yourListedCrops: 'ನಿಮ್ಮ ಪಟ್ಟಿ ಮಾಡಿದ ಬೆಳೆಗಳು',
    noCropsListed: 'ಇನ್ನೂ ಯಾವುದೇ ಬೆಳೆ ಪಟ್ಟಿ ಮಾಡಿಲ್ಲ',
    startByAdding: 'ನಿಮ್ಮ ಮೊದಲ ಬೆಳೆ ಪಟ್ಟಿ ಮಾಡಿ',
    addYourFirstCrop: 'ಮೊದಲ ಬೆಳೆ ಸೇರಿಸಿ',
    listProduce: 'ವ್ಯಾಪಾರಿಗಳಿಗಾಗಿ ನಿಮ್ಮ ಉತ್ಪನ್ನ ಪಟ್ಟಿ ಮಾಡಿ',
    youreOffline: 'ನೀವು ಆಫ್‌ಲೈನ್ ಆಗಿದ್ದೀರಿ',
    cropSavedLocally: 'ಬೆಳೆ ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗುವುದು',
    cropName: 'ಬೆಳೆ ಹೆಸರು',
    cropPhoto: 'ಬೆಳೆ ಫೋಟೊ',
    tapToPhoto: 'ಫೋಟೊ ತೆಗೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    chooseGallery: 'ಅಥವಾ ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಿ',
    photoAdded: 'ಫೋಟೊ ಸೇರಿಸಲಾಗಿದೆ',
    quantity: 'ಪ್ರಮಾಣ',
    pricePerUnit: 'ಪ್ರತಿ ಬೆಲೆ',
    pickupLocation: 'ಪಿಕಪ್ ಸ್ಥಳ',
    detectingLocation: 'ನಿಮ್ಮ ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
    couldntDetect: 'ಸ್ಥಳ ಕಂಡುಬಂದಿಲ್ಲ',
    villageMandi: 'ಹಳ್ಳಿ / ಮಂಡಿ ಹೆಸರು',
    editLocation: 'ಸ್ಥಳ ಸಂಪಾದಿಸಿ',
    pickOnMap: 'ನಕ್ಷೆಯಲ್ಲಿ ಆಯ್ಕೆ',
    detectViaGPS: 'GPS ಮೂಲಕ ಹುಡುಕಿ',
    availableUntil: 'ಲಭ್ಯತೆ ದಿನಾಂಕ',
    totalValue: 'ಒಟ್ಟು ಮೌಲ್ಯ',
    cropListed: 'ಬೆಳೆ ಯಶಸ್ವಿಯಾಗಿ ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ!',
    savedOffline: 'ಆಫ್‌ಲೈನ್ ಉಳಿಸಲಾಗಿದೆ. ಆನ್‌ಲೈನ್ ಆದಾಗ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    listCrop: 'ಬೆಳೆ ಪಟ್ಟಿ ಮಾಡಿ',
    saveOffline: 'ಆಫ್‌ಲೈನ್ ಉಳಿಸಿ',
    cropMarketplace: 'ಬೆಳೆ ಮಾರುಕಟ್ಟೆ',
    browseAndOrder: 'ರೈತರಿಂದ ನೇರವಾಗಿ ತಾಜಾ ಉತ್ಪನ್ನ ಬ್ರೌಸ್ ಮಾಡಿ',
    cropNameFilter: 'ಬೆಳೆ ಹೆಸರು',
    locationFilter: 'ಸ್ಥಳ',
    minPrice: 'ಕನಿಷ್ಠ ₹',
    maxPrice: 'ಗರಿಷ್ಠ ₹',
    searchCrops: 'ಬೆಳೆ ಹುಡುಕಿ',
    cropsAvailable: 'ಬೆಳೆಗಳು ಲಭ್ಯ',
    noCropsFound: 'ಯಾವುದೇ ಬೆಳೆ ಕಂಡುಬಂದಿಲ್ಲ',
    tryAdjusting: 'ಫಿಲ್ಟರ್ ಬದಲಿಸಿ ಅಥವಾ ನಂತರ ನೋಡಿ',
    orderNow: 'ಈಗ ಆರ್ಡರ್ ಮಾಡಿ',
    placeOrder: 'ಆರ್ಡರ್ ಮಾಡಿ',
    reviewCrop: 'ಬೆಳೆ ವಿವರ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ',
    cropNotFound: 'ಬೆಳೆ ವಿವರ ಕಂಡುಬಂದಿಲ್ಲ',
    cropMayNotAvail: 'ಈ ಬೆಳೆ ಈಗ ಲಭ್ಯವಿಲ್ಲದಿರಬಹುದು',
    backToMarketplace: 'ಮಾರುಕಟ್ಟೆಗೆ ಹಿಂತಿರುಗಿ',
    howMuch: 'ನಿಮಗೆ ಎಷ್ಟು ಬೇಕು?',
    maxAvailable: 'ಗರಿಷ್ಠ ಲಭ್ಯ:',
    deliveryLocation: 'ಡೆಲಿವರಿ ಸ್ಥಳ',
    warehouseShop: 'ನಿಮ್ಮ ಗೋದಾಮು / ಅಂಗಡಿ',
    estimatedTotal: 'ಅಂದಾಜು ಒಟ್ಟು',
    orderPlaced: 'ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ!',
    total: 'ಒಟ್ಟು',
    payNow: 'ಈಗ ಪಾವತಿಸಿ',
    placingOrder: 'ಆರ್ಡರ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    confirmOrder: 'ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ',
    yourOrders: 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು',
    manageOrders: 'ವ್ಯಾಪಾರಿಗಳ ಆರ್ಡರ್ ನಿರ್ವಹಿಸಿ',
    pending: 'ಬಾಕಿ',
    active: 'ಸಕ್ರಿಯ',
    accept: 'ಸ್ವೀಕರಿಸಿ',
    reject: 'ತಿರಸ್ಕರಿಸಿ',
    noOrdersYet: 'ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್ ಇಲ್ಲ',
    ordersWillAppear: 'ವ್ಯಾಪಾರಿಗಳ ಆರ್ಡರ್ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ',
    trackOrders: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಮತ್ತು ಪಾವತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    unpaid: 'ಪಾವತಿಯಾಗಿಲ್ಲ',
    paid: 'ಪಾವತಿಸಲಾಗಿದೆ',
    browseMarketplace: 'ಮೊದಲ ಆರ್ಡರ್ ಮಾಡಲು ಮಾರುಕಟ್ಟೆ ಬ್ರೌಸ್ ಮಾಡಿ',
    transporterDashboard: 'ಸಾಗಣೆದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    completed: 'ಪೂರ್ಣ',
    myJobs: 'ನನ್ನ ಕೆಲಸಗಳು',
    delivery: 'ಡೆಲಿವರಿ',
    orderValue: 'ಆರ್ಡರ್ ಮೌಲ್ಯ:',
    pickup: 'ಪಿಕಪ್',
    dropOff: 'ಡ್ರಾಪ್-ಆಫ್',
    acceptJob: 'ಕೆಲಸ ಸ್ವೀಕರಿಸಿ',
    noDeliveryRequests: 'ಸದ್ಯ ಯಾವುದೇ ಡೆಲಿವರಿ ವಿನಂತಿ ಇಲ್ಲ',
    checkBackLater: 'ಹೊಸ ಕೆಲಸಕ್ಕಾಗಿ ನಂತರ ನೋಡಿ',
    noActiveJobs: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಕೆಲಸ ಇಲ್ಲ',
    acceptAvailableJobs: 'ಪ್ರಾರಂಭಿಸಲು ಲಭ್ಯ ಕೆಲಸ ಸ್ವೀಕರಿಸಿ',
    startTransit: 'ಟ್ರಾನ್ಸಿಟ್ ಪ್ರಾರಂಭಿಸಿ',
    markDelivered: 'ಡೆಲಿವರ್ ಆಗಿದೆ',
    deliveryCompleted: 'ಡೆಲಿವರಿ ಪೂರ್ಣ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    payment: 'ಪಾವತಿ',
    completePayment: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ',
    amountToPay: 'ಪಾವತಿ ಮೊತ್ತ',
    connectedParties: 'ಸಂಪರ್ಕಿತ ಪಕ್ಷಗಳು',
    paymentSplitPreview: 'ಪಾವತಿ ವಿಭಜನೆ ದೃಶ್ಯ',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ',
    paymentSuccess: 'ಪಾವತಿ ಯಶಸ್ವಿ!',
    transactionId: 'ವ್ಯವಹಾರ ID',
  },

  te: {
    dashboard: 'డాష్‌బోర్డ్',
    addCrop: 'పంట జోడించు',
    orders: 'ఆర్డర్లు',
    marketplace: 'మార్కెట్',
    myOrders: 'నా ఆర్డర్లు',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    logout: 'లాగ్ అవుట్',
    language: 'భాష',
    farmer: 'రైతు',
    retailer: 'వ్యాపారి',
    transporter: 'రవాణాదారు',
    welcome: 'స్వాగతం',
    totalCrops: 'మొత్తం పంటలు',
    available: 'అందుబాటులో',
    sold: 'అమ్మిన',
    pendingSync: 'సింక్ పెండింగ్',
    addYourFirstCrop: 'మొదటి పంట జోడించు',
    cropName: 'పంట పేరు',
    quantity: 'మొత్తం',
    pricePerUnit: 'ధర ప్రతి',
    pickupLocation: 'పికప్ స్థలం',
    listCrop: 'పంట జాబితా చేయి',
    saveOffline: 'ఆఫ్‌లైన్ సేవ్',
    orderNow: 'ఇప్పుడు ఆర్డర్ చేయి',
    payNow: 'ఇప్పుడు చెల్లించు',
    accept: 'అంగీకరించు',
    reject: 'తిరస్కరించు',
    getStarted: 'ప్రారంభించు',
    login: 'లాగిన్',
    createAccount: 'ఖాతా సృష్టించు',
    welcomeBack: 'తిరిగి స్వాగతం',
    phoneNumber: 'ఫోన్ నంబర్',
    sendOTP: 'OTP పంపు',
    confirmOrder: 'ఆర్డర్ నిర్ధారించు',
    payment: 'చెల్లింపు',
  },

  ta: {
    dashboard: 'டாஷ்போர்டு',
    addCrop: 'பயிர் சேர்',
    orders: 'ஆர்டர்கள்',
    marketplace: 'சந்தை',
    myOrders: 'என் ஆர்டர்கள்',
    online: 'ஆன்லைன்',
    offline: 'ஆஃப்லைன்',
    logout: 'வெளியேறு',
    language: 'மொழி',
    farmer: 'விவசாயி',
    retailer: 'வியாபாரி',
    transporter: 'போக்குவரத்து',
    welcome: 'வரவேற்பு',
    totalCrops: 'மொத்த பயிர்கள்',
    available: 'கிடைக்கும்',
    sold: 'விற்பனை',
    pendingSync: 'ஒத்திசைவு நிலுவை',
    addYourFirstCrop: 'முதல் பயிர் சேர்',
    cropName: 'பயிர் பெயர்',
    quantity: 'அளவு',
    pricePerUnit: 'விலை ஒன்றுக்கு',
    pickupLocation: 'பிக்அப் இடம்',
    listCrop: 'பயிர் பட்டியல்',
    saveOffline: 'ஆஃப்லைன் சேமி',
    orderNow: 'இப்போது ஆர்டர்',
    payNow: 'இப்போது செலுத்து',
    accept: 'ஏற்றுக்கொள்',
    reject: 'நிராகரி',
    getStarted: 'தொடங்கு',
    login: 'உள்நுழைவு',
    createAccount: 'கணக்கு உருவாக்கு',
    welcomeBack: 'மீண்டும் வரவேற்பு',
    phoneNumber: 'தொலைபேசி எண்',
    sendOTP: 'OTP அனுப்பு',
    confirmOrder: 'ஆர்டர் உறுதிப்படுத்து',
    payment: 'பணம் செலுத்துதல்',
  },

  gu: {
    dashboard: 'ડેશબોર્ડ',
    addCrop: 'પાક ઉમેરો',
    orders: 'ઓર્ડર',
    marketplace: 'બજાર',
    myOrders: 'મારા ઓર્ડર',
    online: 'ઓનલાઇન',
    offline: 'ઓફલાઇન',
    logout: 'લોગ આઉટ',
    language: 'ભાષા',
    farmer: 'ખેડૂત',
    retailer: 'વેપારી',
    transporter: 'ટ્રાન્સપોર્ટર',
    welcome: 'સ્વાગત',
    totalCrops: 'કુલ પાક',
    available: 'ઉપલબ્ધ',
    sold: 'વેચાયેલ',
    addYourFirstCrop: 'પહેલો પાક ઉમેરો',
    cropName: 'પાકનું નામ',
    quantity: 'જથ્થો',
    pricePerUnit: 'કિંમત દરેક',
    orderNow: 'હમણાં ઓર્ડર કરો',
    payNow: 'હમણાં ચૂકવો',
    getStarted: 'શરૂ કરો',
    login: 'લોગિન',
    createAccount: 'ખાતું બનાવો',
    welcomeBack: 'ફરી સ્વાગત',
    phoneNumber: 'ફોન નંબર',
    sendOTP: 'OTP મોકલો',
    confirmOrder: 'ઓર્ડર પુષ્ટિ કરો',
    payment: 'ચુકવણી',
  },

  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    addCrop: 'ਫਸਲ ਜੋੜੋ',
    orders: 'ਆਰਡਰ',
    marketplace: 'ਬਾਜ਼ਾਰ',
    myOrders: 'ਮੇਰੇ ਆਰਡਰ',
    online: 'ਆਨਲਾਈਨ',
    offline: 'ਆਫ਼ਲਾਈਨ',
    logout: 'ਲੌਗ ਆਊਟ',
    language: 'ਭਾਸ਼ਾ',
    farmer: 'ਕਿਸਾਨ',
    retailer: 'ਵਪਾਰੀ',
    transporter: 'ਟਰਾਂਸਪੋਰਟਰ',
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    totalCrops: 'ਕੁੱਲ ਫਸਲਾਂ',
    available: 'ਉਪਲਬਧ',
    sold: 'ਵੇਚੀ',
    addYourFirstCrop: 'ਪਹਿਲੀ ਫਸਲ ਜੋੜੋ',
    cropName: 'ਫਸਲ ਦਾ ਨਾਮ',
    quantity: 'ਮਾਤਰਾ',
    pricePerUnit: 'ਕੀਮਤ ਪ੍ਰਤੀ',
    orderNow: 'ਹੁਣੇ ਆਰਡਰ ਕਰੋ',
    payNow: 'ਹੁਣੇ ਭੁਗਤਾਨ ਕਰੋ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    login: 'ਲੌਗਿਨ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    welcomeBack: 'ਫਿਰ ਜੀ ਆਇਆਂ ਨੂੰ',
    phoneNumber: 'ਫ਼ੋਨ ਨੰਬਰ',
    sendOTP: 'OTP ਭੇਜੋ',
    confirmOrder: 'ਆਰਡਰ ਪੁਸ਼ਟੀ ਕਰੋ',
    payment: 'ਭੁਗਤਾਨ',
  },

  bn: {
    dashboard: 'ড্যাশবোর্ড',
    addCrop: 'ফসল যোগ করুন',
    orders: 'অর্ডার',
    marketplace: 'বাজার',
    myOrders: 'আমার অর্ডার',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    logout: 'লগ আউট',
    language: 'ভাষা',
    farmer: 'কৃষক',
    retailer: 'ব্যবসায়ী',
    transporter: 'পরিবহনকারী',
    welcome: 'স্বাগতম',
    totalCrops: 'মোট ফসল',
    available: 'পাওয়া যাচ্ছে',
    sold: 'বিক্রিত',
    addYourFirstCrop: 'প্রথম ফসল যোগ করুন',
    cropName: 'ফসলের নাম',
    quantity: 'পরিমাণ',
    pricePerUnit: 'মূল্য প্রতি',
    orderNow: 'এখনই অর্ডার',
    payNow: 'এখনই পেমেন্ট',
    getStarted: 'শুরু করুন',
    login: 'লগইন',
    createAccount: 'অ্যাকাউন্ট তৈরি',
    welcomeBack: 'আবার স্বাগতম',
    phoneNumber: 'ফোন নম্বর',
    sendOTP: 'OTP পাঠান',
    confirmOrder: 'অর্ডার নিশ্চিত',
    payment: 'পেমেন্ট',
  },
};

// Helper: get translation with fallback to English
function getTranslation(lang, key) {
  return translations[lang]?.[key] || translations.en[key] || key;
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('mandi_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('mandi_lang', lang);
  }, [lang]);

  function t(key) {
    return getTranslation(lang, key);
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export default LanguageContext;
